### PR TITLE
some README updates to prepare for 3.2 merge

### PR DESCRIPTION
**Pull request by jrwest**
TODO:
- [ ] validate all links work
- [ ] verify all the details and class names in "Internals" section are still correct and updated for 3.x
- [ ] add details about how filtering with clustering works
- [ ] run all the examples

### CODE REVIEW

**Comment by jrwest** [comment]
all the links are broken right now because the branch is 3.2-integration or whatever, not master. Should I point them there are or are you planning to merge that branch to master @xedin?

**Comment by jrwest** [comment]
actually, thinking on it a bit more, we probably don't want to link to this repo from doc/sasi.md right?

**Comment by xedin** [comment]
@jrwest Going to merge it into trunk (which is default cassandra branch), I was thinking of putting it into doc/SASI.md since that's where CQL3 documentation and other stuff leaves.

**Comment by xedin** [comment]
Has been incorporated into cassandra/doc/SASI.md

**Pull request closed without merging**
